---
default_set: 'centos-65-x64'
sets:
  'ubuntu-server-12042-x64':
    nodes:
      "main.foo.vm":
        prefab: 'ubuntu-server-12042-x64'
  'centos-65-x64':
    nodes:
      "main.foo.vm":
        prefab: 'centos-65-x64'
  'debian-70rc1-x64':
    nodes:
      "main.foo.vm":
        prefab: 'debian-70rc1-x64'
