source 'https://rubygems.org'

gem 'rake'
gem 'puppet-lint'
gem 'beaker'
gem 'beaker-rspec'
gem 'puppetlabs_spec_helper'
gem 'travis'
gem 'travis-lint'
gem 'guard-rake'
gem 'puppet-syntax'
gem 'puppet', ENV['PUPPET_VERSION'] || '~> 3.3.0'
gem 'vagrant-wrapper'
gem 'puppet-blacksmith'
